// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.example.tutorial.protos;

public interface AddPersonRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddPersonRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tutorial.Person person = 1;</code>
   * @return Whether the person field is set.
   */
  boolean hasPerson();
  /**
   * <code>.tutorial.Person person = 1;</code>
   * @return The person.
   */
  com.example.tutorial.protos.Person getPerson();
  /**
   * <code>.tutorial.Person person = 1;</code>
   */
  com.example.tutorial.protos.PersonOrBuilder getPersonOrBuilder();
}
