// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.example.tutorial.protos;

public interface GetAddressResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.GetAddressResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tutorial.ResponseStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.tutorial.ResponseStatus status = 1;</code>
   * @return The status.
   */
  com.example.tutorial.protos.ResponseStatus getStatus();

  /**
   * <code>.tutorial.AddressBook addressBook = 2;</code>
   * @return Whether the addressBook field is set.
   */
  boolean hasAddressBook();
  /**
   * <code>.tutorial.AddressBook addressBook = 2;</code>
   * @return The addressBook.
   */
  com.example.tutorial.protos.AddressBook getAddressBook();
  /**
   * <code>.tutorial.AddressBook addressBook = 2;</code>
   */
  com.example.tutorial.protos.AddressBookOrBuilder getAddressBookOrBuilder();
}
