// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.example.tutorial.protos;

/**
 * <pre>
 * アドレス帳を取得するレスポンス
 * </pre>
 *
 * Protobuf type {@code tutorial.GetAddressResponse}
 */
public final class GetAddressResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.GetAddressResponse)
    GetAddressResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetAddressResponse.newBuilder() to construct.
  private GetAddressResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetAddressResponse() {
    status_ = 0;
    addressBook_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetAddressResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetAddressResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              addressBook_ = new java.util.ArrayList<com.example.tutorial.protos.AddressBook>();
              mutable_bitField0_ |= 0x00000001;
            }
            addressBook_.add(
                input.readMessage(com.example.tutorial.protos.AddressBook.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        addressBook_ = java.util.Collections.unmodifiableList(addressBook_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_GetAddressResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_GetAddressResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.tutorial.protos.GetAddressResponse.class, com.example.tutorial.protos.GetAddressResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private int status_;
  /**
   * <code>.tutorial.ResponseStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.tutorial.ResponseStatus status = 1;</code>
   * @return The status.
   */
  @java.lang.Override public com.example.tutorial.protos.ResponseStatus getStatus() {
    @SuppressWarnings("deprecation")
    com.example.tutorial.protos.ResponseStatus result = com.example.tutorial.protos.ResponseStatus.valueOf(status_);
    return result == null ? com.example.tutorial.protos.ResponseStatus.UNRECOGNIZED : result;
  }

  public static final int ADDRESSBOOK_FIELD_NUMBER = 2;
  private java.util.List<com.example.tutorial.protos.AddressBook> addressBook_;
  /**
   * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.tutorial.protos.AddressBook> getAddressBookList() {
    return addressBook_;
  }
  /**
   * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.tutorial.protos.AddressBookOrBuilder> 
      getAddressBookOrBuilderList() {
    return addressBook_;
  }
  /**
   * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
   */
  @java.lang.Override
  public int getAddressBookCount() {
    return addressBook_.size();
  }
  /**
   * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
   */
  @java.lang.Override
  public com.example.tutorial.protos.AddressBook getAddressBook(int index) {
    return addressBook_.get(index);
  }
  /**
   * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
   */
  @java.lang.Override
  public com.example.tutorial.protos.AddressBookOrBuilder getAddressBookOrBuilder(
      int index) {
    return addressBook_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != com.example.tutorial.protos.ResponseStatus.SUCCESS.getNumber()) {
      output.writeEnum(1, status_);
    }
    for (int i = 0; i < addressBook_.size(); i++) {
      output.writeMessage(2, addressBook_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != com.example.tutorial.protos.ResponseStatus.SUCCESS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, status_);
    }
    for (int i = 0; i < addressBook_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, addressBook_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.tutorial.protos.GetAddressResponse)) {
      return super.equals(obj);
    }
    com.example.tutorial.protos.GetAddressResponse other = (com.example.tutorial.protos.GetAddressResponse) obj;

    if (status_ != other.status_) return false;
    if (!getAddressBookList()
        .equals(other.getAddressBookList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (getAddressBookCount() > 0) {
      hash = (37 * hash) + ADDRESSBOOK_FIELD_NUMBER;
      hash = (53 * hash) + getAddressBookList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.tutorial.protos.GetAddressResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.tutorial.protos.GetAddressResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.tutorial.protos.GetAddressResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * アドレス帳を取得するレスポンス
   * </pre>
   *
   * Protobuf type {@code tutorial.GetAddressResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.GetAddressResponse)
      com.example.tutorial.protos.GetAddressResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_GetAddressResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_GetAddressResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.tutorial.protos.GetAddressResponse.class, com.example.tutorial.protos.GetAddressResponse.Builder.class);
    }

    // Construct using com.example.tutorial.protos.GetAddressResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAddressBookFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      status_ = 0;

      if (addressBookBuilder_ == null) {
        addressBook_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        addressBookBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.tutorial.protos.AddressBookProtos.internal_static_tutorial_GetAddressResponse_descriptor;
    }

    @java.lang.Override
    public com.example.tutorial.protos.GetAddressResponse getDefaultInstanceForType() {
      return com.example.tutorial.protos.GetAddressResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.tutorial.protos.GetAddressResponse build() {
      com.example.tutorial.protos.GetAddressResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.tutorial.protos.GetAddressResponse buildPartial() {
      com.example.tutorial.protos.GetAddressResponse result = new com.example.tutorial.protos.GetAddressResponse(this);
      int from_bitField0_ = bitField0_;
      result.status_ = status_;
      if (addressBookBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          addressBook_ = java.util.Collections.unmodifiableList(addressBook_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.addressBook_ = addressBook_;
      } else {
        result.addressBook_ = addressBookBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.tutorial.protos.GetAddressResponse) {
        return mergeFrom((com.example.tutorial.protos.GetAddressResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.tutorial.protos.GetAddressResponse other) {
      if (other == com.example.tutorial.protos.GetAddressResponse.getDefaultInstance()) return this;
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (addressBookBuilder_ == null) {
        if (!other.addressBook_.isEmpty()) {
          if (addressBook_.isEmpty()) {
            addressBook_ = other.addressBook_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddressBookIsMutable();
            addressBook_.addAll(other.addressBook_);
          }
          onChanged();
        }
      } else {
        if (!other.addressBook_.isEmpty()) {
          if (addressBookBuilder_.isEmpty()) {
            addressBookBuilder_.dispose();
            addressBookBuilder_ = null;
            addressBook_ = other.addressBook_;
            bitField0_ = (bitField0_ & ~0x00000001);
            addressBookBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAddressBookFieldBuilder() : null;
          } else {
            addressBookBuilder_.addAllMessages(other.addressBook_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.tutorial.protos.GetAddressResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.tutorial.protos.GetAddressResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int status_ = 0;
    /**
     * <code>.tutorial.ResponseStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.tutorial.ResponseStatus status = 1;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.tutorial.ResponseStatus status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.example.tutorial.protos.ResponseStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.example.tutorial.protos.ResponseStatus result = com.example.tutorial.protos.ResponseStatus.valueOf(status_);
      return result == null ? com.example.tutorial.protos.ResponseStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.tutorial.ResponseStatus status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.example.tutorial.protos.ResponseStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tutorial.ResponseStatus status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.example.tutorial.protos.AddressBook> addressBook_ =
      java.util.Collections.emptyList();
    private void ensureAddressBookIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        addressBook_ = new java.util.ArrayList<com.example.tutorial.protos.AddressBook>(addressBook_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.tutorial.protos.AddressBook, com.example.tutorial.protos.AddressBook.Builder, com.example.tutorial.protos.AddressBookOrBuilder> addressBookBuilder_;

    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public java.util.List<com.example.tutorial.protos.AddressBook> getAddressBookList() {
      if (addressBookBuilder_ == null) {
        return java.util.Collections.unmodifiableList(addressBook_);
      } else {
        return addressBookBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public int getAddressBookCount() {
      if (addressBookBuilder_ == null) {
        return addressBook_.size();
      } else {
        return addressBookBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public com.example.tutorial.protos.AddressBook getAddressBook(int index) {
      if (addressBookBuilder_ == null) {
        return addressBook_.get(index);
      } else {
        return addressBookBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder setAddressBook(
        int index, com.example.tutorial.protos.AddressBook value) {
      if (addressBookBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressBookIsMutable();
        addressBook_.set(index, value);
        onChanged();
      } else {
        addressBookBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder setAddressBook(
        int index, com.example.tutorial.protos.AddressBook.Builder builderForValue) {
      if (addressBookBuilder_ == null) {
        ensureAddressBookIsMutable();
        addressBook_.set(index, builderForValue.build());
        onChanged();
      } else {
        addressBookBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder addAddressBook(com.example.tutorial.protos.AddressBook value) {
      if (addressBookBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressBookIsMutable();
        addressBook_.add(value);
        onChanged();
      } else {
        addressBookBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder addAddressBook(
        int index, com.example.tutorial.protos.AddressBook value) {
      if (addressBookBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAddressBookIsMutable();
        addressBook_.add(index, value);
        onChanged();
      } else {
        addressBookBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder addAddressBook(
        com.example.tutorial.protos.AddressBook.Builder builderForValue) {
      if (addressBookBuilder_ == null) {
        ensureAddressBookIsMutable();
        addressBook_.add(builderForValue.build());
        onChanged();
      } else {
        addressBookBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder addAddressBook(
        int index, com.example.tutorial.protos.AddressBook.Builder builderForValue) {
      if (addressBookBuilder_ == null) {
        ensureAddressBookIsMutable();
        addressBook_.add(index, builderForValue.build());
        onChanged();
      } else {
        addressBookBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder addAllAddressBook(
        java.lang.Iterable<? extends com.example.tutorial.protos.AddressBook> values) {
      if (addressBookBuilder_ == null) {
        ensureAddressBookIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addressBook_);
        onChanged();
      } else {
        addressBookBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder clearAddressBook() {
      if (addressBookBuilder_ == null) {
        addressBook_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        addressBookBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public Builder removeAddressBook(int index) {
      if (addressBookBuilder_ == null) {
        ensureAddressBookIsMutable();
        addressBook_.remove(index);
        onChanged();
      } else {
        addressBookBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public com.example.tutorial.protos.AddressBook.Builder getAddressBookBuilder(
        int index) {
      return getAddressBookFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public com.example.tutorial.protos.AddressBookOrBuilder getAddressBookOrBuilder(
        int index) {
      if (addressBookBuilder_ == null) {
        return addressBook_.get(index);  } else {
        return addressBookBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public java.util.List<? extends com.example.tutorial.protos.AddressBookOrBuilder> 
         getAddressBookOrBuilderList() {
      if (addressBookBuilder_ != null) {
        return addressBookBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(addressBook_);
      }
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public com.example.tutorial.protos.AddressBook.Builder addAddressBookBuilder() {
      return getAddressBookFieldBuilder().addBuilder(
          com.example.tutorial.protos.AddressBook.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public com.example.tutorial.protos.AddressBook.Builder addAddressBookBuilder(
        int index) {
      return getAddressBookFieldBuilder().addBuilder(
          index, com.example.tutorial.protos.AddressBook.getDefaultInstance());
    }
    /**
     * <code>repeated .tutorial.AddressBook addressBook = 2;</code>
     */
    public java.util.List<com.example.tutorial.protos.AddressBook.Builder> 
         getAddressBookBuilderList() {
      return getAddressBookFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.tutorial.protos.AddressBook, com.example.tutorial.protos.AddressBook.Builder, com.example.tutorial.protos.AddressBookOrBuilder> 
        getAddressBookFieldBuilder() {
      if (addressBookBuilder_ == null) {
        addressBookBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.tutorial.protos.AddressBook, com.example.tutorial.protos.AddressBook.Builder, com.example.tutorial.protos.AddressBookOrBuilder>(
                addressBook_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        addressBook_ = null;
      }
      return addressBookBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tutorial.GetAddressResponse)
  }

  // @@protoc_insertion_point(class_scope:tutorial.GetAddressResponse)
  private static final com.example.tutorial.protos.GetAddressResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.tutorial.protos.GetAddressResponse();
  }

  public static com.example.tutorial.protos.GetAddressResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetAddressResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetAddressResponse>() {
    @java.lang.Override
    public GetAddressResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetAddressResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetAddressResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetAddressResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.tutorial.protos.GetAddressResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

