// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.example.tutorial.protos;

public interface GetPersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.GetPersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tutorial.ResponseStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.tutorial.ResponseStatus status = 1;</code>
   * @return The status.
   */
  com.example.tutorial.protos.ResponseStatus getStatus();

  /**
   * <code>.tutorial.Person person = 2;</code>
   * @return Whether the person field is set.
   */
  boolean hasPerson();
  /**
   * <code>.tutorial.Person person = 2;</code>
   * @return The person.
   */
  com.example.tutorial.protos.Person getPerson();
  /**
   * <code>.tutorial.Person person = 2;</code>
   */
  com.example.tutorial.protos.PersonOrBuilder getPersonOrBuilder();
}
