// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.example.tutorial.protos;

public interface UpdatePersonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.UpdatePersonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tutorial.ResponseStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.tutorial.ResponseStatus status = 1;</code>
   * @return The status.
   */
  com.example.tutorial.protos.ResponseStatus getStatus();
}
